name: Check Swift app
on: [pull_request, push]
jobs:
  build:
    runs-on: Ubuntu-18.04
    container:
      image: ghcr.io/swiftwasm/carton:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: carton bundle
